source = /home/asithakanchana/.config/hypr/config/theme.conf
source = /home/asithakanchana/.config/hypr/config/monitors-programs.conf
source = /home/asithakanchana/.config/hypr/config/autostart.conf
source = /home/asithakanchana/.config/hypr/config/appearance.conf
source = /home/asithakanchana/.config/hypr/config/input.conf
source = /home/asithakanchana/.config/hypr/config/bindings.conf
source = /home/asithakanchana/.config/hypr/config/environment-rules.conf
