env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = GTK_THEME,Adwaita:dark
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = GDK_SCALE,2

xwayland {
    force_zero_scaling = true
}

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}
windowrule {
    name = nmtui-float
    match:class = ^(floating_nmtui)$
    float = on
    center = on
    size = 600 400
}
windowrule {
    name = microsoft-office-apps
    match:title = ^(Microsoft .*)$
    float = true
    size = 1200 800
    center = true
}
windowrule {
    name = nmtui-waybar-float
    match:class = ^(nmtui-float)$
    float = on
    center = on
    size = 700 500
}
windowrule = float 1, match:class ^(Zoom Workplace)$, match:title ^(as_toolbar)$
windowrule = float 1, match:class ^(zoom)$, match:title ^(as_toolbar)$
windowrule = pin 1, match:class ^(Zoom Workplace)$, match:title ^(as_toolbar)$
windowrule = pin 1, match:class ^(zoom)$, match:title ^(as_toolbar)$
windowrule = border_size 0, match:class ^(Zoom Workplace)$, match:title ^(as_toolbar)$
windowrule = border_size 0, match:class ^(zoom)$, match:title ^(as_toolbar)$
windowrule = animation none, match:title ^(as_toolbar)$